server:
  port : 9115
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname : localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:9113/eureka/
#请求超时时间
provider:
  ribbon:
    ReadTimeOut: 1000
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true