server:
  port : 9115
spring:
  application:
    name: consumer
eureka:
  instance:
    hostname : localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:9113/eureka/
